(() => {
  let id = 0;
  const bank = [];
  const add = (topic, question, correct, wrong, explanation) => {
    const options = [correct, ...wrong];
    const shift = id % 4;
    const rotated = options.slice(shift).concat(options.slice(0, shift));
    bank.push({ id: `q${++id}`, topic, question, options: rotated, answer: rotated.indexOf(correct), explanation });
  };

  const T = {
    foundations: 'Foundations, Bias & Statistics',
    variables: 'Variables & Study Roles',
    measurement: 'Data Types & Measurement Scales',
    center: 'Central Tendency, Frequency & Proportion',
    distribution: 'Distributions, Skew & Box Plots',
    spread: 'Variability, SD & Sampling',
    zci: 'Z-Scores & Confidence Intervals',
    questions: 'Research Questions, PICO & Hypotheses',
    errors: 'Null Hypothesis, Errors, Power & Tails',
    reliability: 'Measurement Reliability & Error',
    validity: 'Measurement Validity',
    studyValidity: 'Internal & External Study Validity',
    evidence: 'Research Evidence & Articles'
  };

  // 1. Foundations, Bias & Statistics
  add(T.foundations, 'Which statement best captures the common theme in the lecture definitions of research?', 'Research is a systematic method of asking and answering questions.', ['Research is any collection of numerical data.', 'Research is an expert opinion supported by tradition.', 'Research is a process that always proves a theory.'], 'Across the definitions, the repeated ideas are systematic inquiry, objective observation, and answering questions.');
  add(T.foundations, 'A clinician assumes a complication is common because two recent patients experienced it. Which bias is most evident?', 'Availability heuristic', ['Confirmation bias', 'Belief bias', 'Fundamental attribution error'], 'The availability heuristic makes familiar or easily recalled events seem more common than they are.');
  add(T.foundations, 'A researcher notices evidence supporting a preferred treatment but discounts evidence against it. This is:', 'Confirmation bias', ['Availability heuristic', 'Sampling error', 'Fundamental attribution error'], 'Confirmation bias is the tendency to favor evidence that supports an existing belief or desired conclusion.');
  add(T.foundations, 'A dentist attributes a patient’s missed visits entirely to laziness while ignoring transportation barriers. This illustrates:', 'Fundamental attribution error', ['Belief bias', 'Availability heuristic', 'Regression to the mean'], 'Fundamental attribution error overemphasizes personal characteristics and underestimates environmental influences.');
  add(T.foundations, 'Which source of knowing is based primarily on sense and observation?', 'Empiricism', ['Rationalism', 'Authority', 'Tradition'], 'Empiricism relies on personal experience, sensing, and observing.');
  add(T.foundations, 'A statistic is best defined as:', 'A single number used to describe or analyze data from a sample', ['Every individual value collected from a population', 'A theory that explains a research result', 'A conclusion that is guaranteed to be correct'], 'The lecture defines a statistic as a single number describing a sample data set or analyzing those data.');
  add(T.foundations, 'A paper reports the participants’ mean age, sex distribution, and average plaque score. These are primarily:', 'Descriptive statistics', ['Inferential statistics', 'Operational definitions', 'Causal hypotheses'], 'Descriptive statistics summarize what the observed group and its scores are like.');
  add(T.foundations, 'A study uses a sample to decide whether two treatments differ in the target population. This is primarily:', 'Inferential statistics', ['Descriptive statistics', 'Qualitative coding', 'Face validation'], 'Inferential statistics use sample information to compare groups or draw conclusions about a population.');
  add(T.foundations, 'Which is an inferential statistical procedure named in the introductory lecture?', 'ANOVA', ['Median', 'Frequency', 'Range'], 'ANOVA, t tests, correlation, regression, and chi-square were introduced as inferential procedures.');
  add(T.foundations, 'Which sequence best represents the closed-loop research process?', 'Question → hypothesis → plan → data → interpretation → new questions', ['Data → proof → tradition → question', 'Hypothesis → conclusion → observations → plan', 'Question → conclusion → data → hypothesis'], 'Research begins with a question, develops a hypothesis and plan, collects and interprets data, and generates new questions.');

  // 2. Variables & Study Roles
  add(T.variables, 'In a study testing whether a fluoride varnish reduces new caries, varnish condition is the:', 'Independent variable', ['Dependent variable', 'Outcome statistic', 'Sampling error'], 'The independent variable is the explanatory or predictor variable expected to affect an outcome.');
  add(T.variables, 'In that fluoride-varnish study, number of new caries lesions is the:', 'Dependent variable', ['Independent variable', 'Control variable', 'Population parameter'], 'The dependent variable is the primary outcome thought to be affected by another variable.');
  add(T.variables, 'Researchers hold brushing frequency constant because it could influence caries but is not their main interest. Brushing frequency is a:', 'Control or confounding variable', ['Dependent variable', 'Random error', 'Criterion measure'], 'A control variable is a potential confounder the researcher attempts to hold constant or account for.');
  add(T.variables, 'Which statement about a variable’s independent/dependent designation is correct?', 'Its designation depends on its role in the specific study.', ['The designation is an inherent property of the variable.', 'Age must always be an independent variable.', 'Only manipulated variables can ever be independent variables.'], 'The same variable can play different roles in different studies; orientation is study-specific.');
  add(T.variables, 'An experiment gives children either a powered or manual toothbrush and later measures plaque. What is directly manipulated?', 'Type of toothbrush', ['Plaque score', 'Child age', 'Sample size'], 'In an experiment, the manipulated condition is the independent variable.');
  add(T.variables, 'A study examines whether stress predicts test performance. Which pairing is most consistent with that wording?', 'Stress = independent; test performance = dependent', ['Stress = dependent; test performance = control', 'Stress = control; test performance = independent', 'Both variables must be dependent'], 'The proposed predictor is stress; the proposed outcome is test performance.');
  add(T.variables, 'Why might age be controlled in a study of toothpaste type and stain removal?', 'Age may also affect staining and therefore confound the toothpaste–outcome relationship.', ['Age is always the primary outcome.', 'Controlling age changes it into a nominal variable.', 'Every study must manipulate age.'], 'A confounder may influence the dependent variable without being the primary variable of interest.');
  add(T.variables, 'Which best describes a conceptual definition of anxiety?', 'A statement identifying the major meaning and aspects of anxiety', ['A score of 20 or higher on a named anxiety scale', 'The number of participants in the anxiety group', 'The arithmetic mean of anxiety scores'], 'A conceptual definition explains what the construct means; it does not yet specify the concrete measurement procedure.');
  add(T.variables, 'Which is an operational definition of pre-exam confidence?', 'A student’s score on a five-item confidence questionnaire administered before the exam', ['A belief that confidence matters', 'The general feeling of being confident', 'A theory about why students feel confident'], 'An operational definition translates a construct into observable, concrete, measurable characteristics.');
  add(T.variables, 'All experimental studies described in lecture must include at least:', 'One independent variable and one dependent variable', ['One ratio variable and one nominal variable', 'Two dependent variables', 'One confounder that cannot be controlled'], 'The lecture states that all studies have at least one independent and one dependent variable.');

  // 3. Data Types & Scales
  add(T.measurement, 'Which variable is nominal?', 'Blood type', ['Pain severity rated mild/moderate/severe', 'Temperature in Celsius', 'Body weight in kilograms'], 'Nominal values name categories without an inherent order.');
  add(T.measurement, 'Which variable is ordinal?', 'Class rank', ['Eye color', 'Temperature in Fahrenheit', 'Time in seconds'], 'Ordinal values have a meaningful order but unequal or unspecified distances between ranks.');
  add(T.measurement, 'Which variable is interval?', 'Temperature in Celsius', ['Number of teeth', 'Weight in kilograms', 'Political party'], 'Interval data have equal distances, but zero does not represent absence of the characteristic.');
  add(T.measurement, 'Which variable is ratio?', 'Time required to complete a procedure', ['Letter grade', 'Temperature in Celsius', 'Marital status'], 'Ratio data have equal intervals and a meaningful zero, so ratios can be interpreted.');
  add(T.measurement, 'What makes levels of measurement cumulative?', 'Each higher level contains the properties of the levels below it.', ['Every variable can be converted upward without information.', 'All four levels permit the same analyses.', 'Ratio data contain fewer properties than nominal data.'], 'The hierarchy is cumulative, but data can only be safely converted to a lower level, not upgraded.');
  add(T.measurement, 'A survey response of “yes” or “no” is usually:', 'Dichotomous nominal data', ['Continuous ratio data', 'Ordinal interval data', 'Qualitative data with no categories'], 'Two unordered categories form dichotomous nominal data.');
  add(T.measurement, 'The number of children in a household is:', 'Discrete because it is count data that cannot meaningfully be subdivided', ['Continuous because every number is quantitative', 'Nominal because children are categories', 'Interval because zero is arbitrary'], 'Discrete variables use separate countable units, such as 0, 1, 2, or 3 children.');
  add(T.measurement, 'A patient’s weight is usually treated as:', 'Continuous ratio data', ['Discrete ordinal data', 'Continuous interval data', 'Nominal data'], 'Weight can be subdivided and has a true zero, making it continuous ratio data.');
  add(T.measurement, 'Age recorded as <40, 40–54, 55–64, or ≥65 is best classified as:', 'Ordinal categorical data', ['Ratio continuous data', 'Nominal data', 'Interval continuous data'], 'Grouping numerical age into ordered bands changes the recorded variable into ordinal categories.');
  add(T.measurement, 'Why can continuous versus discrete sometimes depend on the measurement tool?', 'A tool’s precision may restrict which subdivisions can actually be recorded.', ['The tool changes nominal values into ratio values.', 'All measured values are automatically discrete.', 'Only qualitative variables require tools.'], 'The lecture notes that the continuous/discrete distinction can be conditional on measurement precision.');
  add(T.measurement, 'Which feature most strongly suggests a quantitative rather than qualitative study?', 'A specific objective measure collected from a large sample', ['Flexible open-ended interviews with a small purposeful sample', 'Data collection that changes as themes emerge', 'Minimal prior knowledge of the phenomenon'], 'Quantitative work typically uses specific, objective measures and larger samples.');

  // 4. Central Tendency, Frequency & Proportion
  add(T.center, 'Measures of central tendency reduce a data set to:', 'A single estimate of its middle or central value', ['A measure of causal effect', 'A list of every score', 'The population sampling frame'], 'Mean, median, and mode are alternative summaries of the center of a distribution.');
  add(T.center, 'Which measure is the balancing point and is pulled toward extreme values?', 'Mean', ['Median', 'Mode', 'Interquartile range'], 'The arithmetic mean uses every score, so extreme scores can pull it toward the tail.');
  add(T.center, 'Which measure identifies the middle ordered observation?', 'Median', ['Mean', 'Mode', 'Standard deviation'], 'The median divides an ordered distribution so half the observations are above and half below.');
  add(T.center, 'Which measure can appropriately summarize a nominal variable?', 'Mode', ['Mean only', 'Median only', 'Standard deviation only'], 'The mode simply identifies the most frequent category, so it can be used with nominal data.');
  add(T.center, 'Household incomes are strongly right-skewed by a few extremely high values. The best typical-income summary is usually the:', 'Median', ['Mean', 'Range', 'Variance'], 'The median is resistant to extreme values, whereas the mean is pulled toward the high-income tail.');
  add(T.center, 'A distribution with two equally prominent most-common scores is:', 'Bimodal', ['Symmetrical by definition', 'Platykurtic by definition', 'Without any central tendency'], 'Bimodal means that two values or regions act as modes; one mode may not summarize it well.');
  add(T.center, 'Which central-tendency measures are conventionally appropriate for interval or ratio data?', 'Mean, median, and mode', ['Mode only', 'Median and mode only', 'Mean only'], 'Interval/ratio data support all three; the best choice still depends on distribution and purpose.');
  add(T.center, 'Why is a raw frequency of five home runs hard to interpret by itself?', 'It lacks the number of opportunities, such as at-bats.', ['Frequency can only describe nominal variables.', 'Five cannot be used in statistical analysis.', 'A frequency always requires a z-score.'], 'When opportunities differ, a proportion corrects the count using a meaningful denominator.');
  add(T.center, 'A clinic had 24 missed appointments out of 300 scheduled appointments. Which value is the relevant proportion?', '24 ÷ 300', ['300 ÷ 24', '24 + 300', '24 × 300'], 'A proportion is the subgroup or event count divided by the relevant total count.');
  add(T.center, 'When a test has a fixed number of equally scored items, why may a total score be adequate?', 'Every person has the same maximum number of opportunities.', ['The total becomes nominal.', 'Proportions cannot be computed from tests.', 'Fixed tests eliminate all measurement error.'], 'With a fixed denominator, totals and proportions preserve the same ordering and information.');

  // 5. Distributions, Skew & Box Plots
  add(T.distribution, 'In a perfectly symmetrical unimodal distribution, the mean, median, and mode are:', 'Equal', ['Ordered mean < median < mode', 'Ordered mode < median < mean', 'Unrelated'], 'In the ideal symmetric unimodal case, all three measures meet at the center.');
  add(T.distribution, 'In a positively skewed distribution, the long tail extends:', 'To the right, toward larger values', ['To the left, toward smaller values', 'Equally in both directions', 'Only above the mode'], 'The lecture memory cue is “skew = tail”; positive/right skew has a long right tail.');
  add(T.distribution, 'Which order is expected in a positively skewed distribution?', 'Mode < median < mean', ['Mean < median < mode', 'Mean = median = mode', 'Median < mean < mode'], 'The right-side extreme values pull the mean farthest right, with the median between mean and mode.');
  add(T.distribution, 'Which order is expected in a negatively skewed distribution?', 'Mean < median < mode', ['Mode < median < mean', 'Mean = median = mode', 'Mode < mean < median'], 'The left-side extreme values pull the mean farthest toward the negative tail.');
  add(T.distribution, 'The range equals:', 'Largest value minus smallest value', ['Q3 minus Q1', 'Mean divided by SD', 'Median minus mode'], 'Range measures the full observed span from minimum to maximum.');
  add(T.distribution, 'The interquartile range represents:', 'The middle 50% of the data and equals Q3 − Q1', ['The full range divided by four', 'All values within one SD', 'The distance from the mean to the mode'], 'Q1 is the 25th percentile and Q3 the 75th, so their difference spans the middle half.');
  add(T.distribution, 'Using the lecture rule, a value is an outlier if it lies:', 'More than 1.5 IQR below Q1 or above Q3', ['More than 1 SD from the mean', 'Outside the minimum and maximum', 'Above the median only'], 'The box-plot fences are Q1 − 1.5(IQR) and Q3 + 1.5(IQR).');
  add(T.distribution, 'For Q1 = 20 and Q3 = 32, what is the upper outlier fence?', '50', ['44', '38', '62'], 'IQR = 12; 1.5 × 12 = 18; upper fence = 32 + 18 = 50.');
  add(T.distribution, 'A box plot has a much longer left whisker and the median sits near Q3. What shape is suggested?', 'Negative (left) skew', ['Positive (right) skew', 'Perfect symmetry', 'Bimodality'], 'A longer left-side extension indicates a longer left tail and negative skew.');
  add(T.distribution, 'Kurtosis is most directly concerned with:', 'Tail heaviness and the likelihood of extreme observations', ['The direction of skew only', 'The arithmetic average', 'Whether data are nominal'], 'Kurtosis characterizes tail weight/outlier tendency, not simply overall spread or skew direction.');
  add(T.distribution, 'Compared with a normal distribution, a leptokurtic distribution generally has:', 'Heavier tails and more extreme values', ['Lighter tails and fewer extreme values', 'No variability', 'A required positive skew'], 'Leptokurtic distributions have heavier tails; platykurtic distributions have lighter tails.');

  // 6. Variability, SD & Sampling
  add(T.spread, 'Standard deviation describes:', 'Dispersion of scores around the mean', ['The most common category', 'The direction of causation', 'The number of variables'], 'A low SD means scores cluster near the mean; a high SD means they are more spread out.');
  add(T.spread, 'Variance is technically:', 'The average of squared deviations from the mean', ['The square root of the range', 'The median minus the mode', 'The mean of the raw scores squared'], 'Variance is based on squared distances from the mean; SD is the square root of variance.');
  add(T.spread, 'Why are deviations squared when computing variance?', 'Squaring prevents positive and negative deviations from cancelling.', ['It converts every variable to ratio data.', 'It removes all outliers.', 'It makes the sample equal the population.'], 'Raw signed deviations sum to zero around the mean, so squaring permits a nonzero measure of spread.');
  add(T.spread, 'Why take the square root of variance to obtain SD?', 'It returns the spread measure to the original units of the variable.', ['It eliminates sampling error.', 'It makes SD insensitive to outliers.', 'It converts the mean to a percentile.'], 'Variance uses squared units; the square root restores interpretable original units.');
  add(T.spread, 'For a sample, the variance denominator is usually:', 'n − 1', ['n', 'n + 1', '√n'], 'Bessel’s correction uses n − 1 for a sample; a full population uses N.');
  add(T.spread, 'Can two standard deviations from variables with very different means and units be compared directly?', 'No; SD must be interpreted in the context of the variable and its mean.', ['Yes; the larger SD always means poorer data.', 'Yes, but only if both samples are small.', 'No, because SD can never be compared.'], 'The lecture cautions against comparing raw SDs across variables without context; equal means allow a more direct comparison.');
  add(T.spread, 'The lecture’s rough warning rule says to be wary when:', 'SD is greater than half the mean', ['SD is smaller than the mean', 'The median equals the mean', 'The sample exceeds 30'], 'A very large SD relative to the mean suggests substantial heterogeneity and may complicate interpretation.');
  add(T.spread, 'A population is:', 'The whole group about which the researcher is interested', ['Any subset chosen for measurement', 'Only the participants who finish a study', 'A sample containing exactly 30 people'], 'A sample is selected from the population; a census includes the whole population.');
  add(T.spread, 'Sampling error is the:', 'Difference between a sample statistic and the corresponding population parameter', ['Mistake made when entering data', 'Inconsistency between two observers', 'Effect of question wording'], 'Samples only estimate population values, so some discrepancy is expected even with proper random selection.');
  add(T.spread, 'According to the central limit theorem, as sample size grows, the sampling distribution of the mean:', 'Approaches normality regardless of the population’s original shape', ['Becomes increasingly skewed', 'Must equal the raw population distribution', 'Loses its mean'], 'The central limit theorem explains why sampling distributions tend toward normality with larger n.');
  add(T.spread, 'As sample size increases, sampling error generally:', 'Decreases', ['Increases', 'Remains exactly constant', 'Becomes measurement error'], 'Larger random samples produce more stable estimates and smaller standard errors.');

  // 7. Z-scores & Confidence Intervals
  add(T.zci, 'A z-score states:', 'How many standard deviations a score is above or below the mean', ['The percentage of scores identical to the mean', 'The sample size needed for significance', 'The width of a box plot'], 'The sign gives direction and the magnitude gives standardized distance from the mean.');
  add(T.zci, 'A z-score of 0 means the raw score is:', 'Exactly at the mean', ['At the 0th percentile', 'One SD below the mean', 'An outlier'], 'Subtracting the mean from an equal raw score produces zero.');
  add(T.zci, 'A z-score of −1.8 describes a score that is:', '1.8 standard deviations below the mean', ['1.8 points below the mean', '1.8 standard deviations above the mean', 'At the 18th percentile by definition'], 'Negative z-scores fall below the mean; units are standard deviations, not raw points.');
  add(T.zci, 'A test mean is 80, SD is 10, and a student scores 95. What is the z-score?', '1.5', ['−1.5', '0.67', '15'], 'z = (95 − 80) ÷ 10 = 1.5.');
  add(T.zci, 'A z-score of +1.00 corresponds approximately to which percentile?', '84th percentile', ['16th percentile', '50th percentile', '99th percentile'], 'About 84% of a normal distribution lies below z = +1.00.');
  add(T.zci, 'A confidence interval is best interpreted as:', 'A range calculated to have a specified chance of containing the population parameter', ['The range containing every sample observation', 'Proof that the sample mean equals the population mean', 'The probability that each participant is correct'], 'A CI quantifies uncertainty around an estimate of a population parameter.');
  add(T.zci, 'The two endpoints of a confidence interval are called:', 'Lower and upper confidence limits', ['Type I and Type II limits', 'Quartiles and whiskers', 'Sample and population errors'], 'The endpoints are commonly abbreviated as lower and upper confidence limits.');
  add(T.zci, 'Holding everything else constant, increasing sample size makes a confidence interval:', 'Narrower', ['Wider', 'Shift to zero', 'Change from two-tailed to one-tailed'], 'Standard error varies inversely with √n; greater n reduces uncertainty and CI width.');
  add(T.zci, 'If sample size is quadrupled, standard error and CI width are approximately:', 'Cut in half', ['Doubled', 'Cut to one quarter', 'Unchanged'], 'Because uncertainty depends on 1/√n, multiplying n by 4 divides it by √4 = 2.');
  add(T.zci, 'Holding n and SD constant, changing from a 90% CI to a 99% CI makes the interval:', 'Wider', ['Narrower', 'Identical', 'Centered at zero'], 'More confidence requires a larger critical z-value and therefore a wider interval.');
  add(T.zci, 'Holding other factors constant, greater population variation makes the confidence interval:', 'Wider', ['Narrower', 'Unchanged', 'Necessarily invalid'], 'Higher SD raises the standard error and expands the margin of error.');
  add(T.zci, 'In the lecture CI formula for a mean, the margin of error is:', 'Critical z × sample SD ÷ √n', ['Sample mean × n', 'Critical z ÷ sample mean', 'IQR × n'], 'The interval is sample mean ± the critical z-value times the standard error.');
  add(T.zci, 'A 95% confidence level uses which approximate critical z-value?', '1.96', ['0.674', '1.282', '2.576'], 'The lecture table gives 1.96 for 95%; 2.576 corresponds to 99%.');

  // 8. Research Questions, PICO & Hypotheses
  add(T.questions, 'A background clinical question usually asks for:', 'Broad, general knowledge about a condition, test, or treatment', ['A comparison tailored to one clinical decision', 'A causal conclusion from an experiment', 'A specific statistical test'], 'Background questions supply foundational “forest” knowledge and commonly use a question root plus the condition or treatment.');
  add(T.questions, 'A foreground clinical question is designed to:', 'Provide focused information for a clinical decision or action', ['Summarize basic textbook knowledge only', 'Avoid identifying an outcome', 'Replace a research hypothesis'], 'Foreground questions are specific “trees” questions and in health research are commonly structured with PICO.');
  add(T.questions, 'In PICO, P represents:', 'Patient, population, or problem', ['Prediction', 'Procedure', 'Probability'], 'P identifies the patient group or clinical problem of interest.');
  add(T.questions, 'In PICO, I represents:', 'Intervention, exposure, or prognostic factor', ['Inference', 'Instrument', 'Internal validity'], 'I is the main action, exposure, or factor being considered.');
  add(T.questions, 'In PICO, C represents:', 'Comparison or alternative', ['Confidence interval', 'Causal mechanism', 'Continuous variable'], 'C specifies the alternative against which the intervention or exposure is evaluated.');
  add(T.questions, 'In PICO, O represents:', 'Outcome to accomplish, measure, improve, or affect', ['Observer', 'Operational definition', 'Original article'], 'O is the patient-relevant result being measured.');
  add(T.questions, 'Which is the strongest foreground question?', 'In adults with gingivitis, does powered brushing versus manual brushing reduce gingival bleeding after eight weeks?', ['What is gingivitis?', 'Are powered toothbrushes good?', 'Why do people brush their teeth?'], 'It clearly specifies a population, intervention, comparison, outcome, and time frame.');
  add(T.questions, 'Which question is too subjective as written?', 'Are electronic toothbrushes good for children?', ['How does electronic toothbrush use correlate with early childhood caries?', 'What percentage of children use electronic toothbrushes?', 'Does powered brushing reduce plaque scores compared with manual brushing?'], '“Good” is vague and lacks an objective measurable outcome.');
  add(T.questions, 'How does a hypothesis differ from a research question?', 'A hypothesis predicts an expected relationship or difference.', ['A hypothesis cannot mention variables.', 'A research question always claims causation.', 'Only a question can be tested.'], 'A question asks; a hypothesis states a prediction that can be evaluated.');
  add(T.questions, '“Stress and test performance will be significantly related” is:', 'A non-directional relational hypothesis', ['A directional causal hypothesis', 'A null hypothesis', 'A background question'], 'It predicts a relationship but does not specify whether performance rises or falls with stress.');
  add(T.questions, '“As stress increases, test performance will decrease” is:', 'A directional relational hypothesis', ['A non-directional causal hypothesis', 'A null hypothesis', 'A background question'], 'It predicts the direction of association but does not state that stress causes the change.');
  add(T.questions, '“Increased stress causes lower test performance” is:', 'A directional causal hypothesis', ['A non-directional relational hypothesis', 'A descriptive statistic', 'A PICO comparison'], 'Causal hypotheses must specify a direction and claim that one variable produces change in another.');

  // 9. Null, Errors, Power & Tails
  add(T.errors, 'The null hypothesis usually states that:', 'There is no population difference or relationship', ['The researcher’s preferred prediction is true', 'The sample mean must be zero', 'All measurements are valid'], 'H₀ expresses no effect, no difference, or no relationship in the population.');
  add(T.errors, 'If results are statistically significant, the appropriate conclusion is usually:', 'Reject the null hypothesis', ['Prove the research hypothesis', 'Accept every alternative explanation', 'Reject the sample'], 'Evidence may be sufficient to reject H₀, but science does not “prove” the preferred hypothesis.');
  add(T.errors, 'If results are not statistically significant, the appropriate wording is:', 'Fail to reject the null hypothesis', ['Prove the null hypothesis', 'Reject the research participants', 'Confirm no effect can ever exist'], 'Failure to reject means the data were insufficient to disprove H₀; it is not definitive proof of no effect.');
  add(T.errors, 'A Type I error occurs when a researcher:', 'Rejects a true null hypothesis', ['Fails to reject a false null hypothesis', 'Rejects a false null hypothesis', 'Fails to reject a true null hypothesis'], 'Type I error is a false positive—“hallucinating” a significant result that is not real.');
  add(T.errors, 'A Type II error occurs when a researcher:', 'Fails to reject a false null hypothesis', ['Rejects a true null hypothesis', 'Rejects a false null hypothesis', 'Fails to reject a true null hypothesis'], 'Type II error is a false negative—being “blind” to a real difference.');
  add(T.errors, 'Alpha is the researcher’s chosen maximum probability of:', 'A Type I error', ['A Type II error', 'A correct rejection', 'Sampling from the population'], 'An alpha of .05 tolerates a 5% chance of a false-positive conclusion under the statistical model.');
  add(T.errors, 'Beta is associated with:', 'The probability of a Type II error', ['The probability of a Type I error', 'The confidence level only', 'The sample mean'], 'Beta represents false-negative risk. Statistical power equals 1 − beta.');
  add(T.errors, 'If beta = .20, statistical power equals:', '.80', ['.20', '.05', '1.20'], 'Power = 1 − β = 1 − .20 = .80.');
  add(T.errors, 'Which change generally increases statistical power?', 'Increasing sample size', ['Making alpha extremely small', 'Using a less reliable measure', 'Designing the study to detect a tinier effect with the same n'], 'Larger samples, reliable measures, and defensible design choices improve the chance of detecting a real effect.');
  add(T.errors, 'Lowering alpha from .05 to .01 generally:', 'Decreases Type I risk but increases Type II risk', ['Increases both Type I and Type II risk', 'Decreases both risks with no tradeoff', 'Changes beta to zero'], 'A more conservative significance threshold reduces false positives but makes real effects harder to detect.');
  add(T.errors, 'With alpha = .05 in a two-tailed test, the error area is:', '2.5% in each tail', ['5% in each tail', '5% in the positive tail only', '2.5% total'], 'A two-tailed test divides the total .05 alpha equally between both directions.');
  add(T.errors, 'When is a one-tailed test most defensible?', 'When the untested direction is genuinely irrelevant or negligible and direction was chosen before analysis', ['Whenever a two-tailed result is almost significant', 'After seeing which direction the sample favors', 'Whenever the researcher wants a smaller p-value'], 'Tail choice should follow theory and consequences, not be changed after examining results.');

  // 10. Reliability & Error
  add(T.reliability, 'Measurement reliability refers to:', 'Consistency of results', ['Accuracy of what is measured', 'Generalizability to a population', 'Absence of sampling error'], 'Reliability concerns stability across raters, time, forms, or items.');
  add(T.reliability, 'Reliability is best described as:', 'Necessary but not sufficient for validity', ['Identical to validity', 'Sufficient but not necessary for validity', 'Unrelated to validity'], 'A measure must be consistent to be valid, but it can consistently measure the wrong thing.');
  add(T.reliability, 'Two examiners independently score the same radiographs. Their agreement assesses:', 'Inter-rater reliability', ['Test–retest reliability', 'Parallel-forms reliability', 'Predictive validity'], 'Inter-rater reliability asks whether results remain consistent across observers.');
  add(T.reliability, 'The best way to improve agreement among multiple clinical raters is typically:', 'Calibration using common scoring rules and examples', ['Increasing face validity only', 'Using a smaller sample', 'Changing the outcome after data collection'], 'Training and calibration align raters’ use of the scoring criteria.');
  add(T.reliability, 'Administering the same stable measure twice to the same people primarily assesses:', 'Test–retest reliability', ['Inter-rater reliability', 'Content validity', 'External validity'], 'Test–retest reliability evaluates stability over time, with timing chosen to limit memory and real change.');
  add(T.reliability, 'Giving equivalent Form A and Form B of an exam assesses:', 'Parallel-forms reliability', ['Internal validity', 'Predictive validity', 'Sampling reliability'], 'Equivalent forms should have comparable structure, content, and difficulty and produce similar scores.');
  add(T.reliability, 'Split-half reliability is a form of:', 'Internal consistency', ['External validity', 'Inter-rater reliability', 'Test–retest reliability'], 'Internal consistency asks whether items within one administration measure coherently.');
  add(T.reliability, 'Observed score is commonly conceptualized as:', 'True score plus measurement error', ['True score minus sample size', 'Mean plus validity', 'Population score plus alpha'], 'Observed values include the underlying true score and unavoidable measurement error.');
  add(T.reliability, 'A survey item is ambiguous and different respondents interpret it differently. This is primarily:', 'Measurement error', ['Sampling error', 'External validity', 'A Type I error'], 'Ambiguous questions make the instrument capture responses inconsistently or inaccurately.');
  add(T.reliability, 'Sampling error differs from measurement error because sampling error comes from:', 'Using a sample to estimate a population', ['Inconsistent raters', 'Biased item wording', 'Unreliable equipment'], 'Sampling error is sample-to-population discrepancy; measurement error arises while measuring cases.');
  add(T.reliability, 'A survey is so long that certain participants stop before completion. The lecture identifies this as a potential source of:', 'Non-response bias', ['Parallel-forms reliability', 'Content validity', 'Regression to the mean'], 'Length, sensitivity, readability, and appeal can systematically affect who responds or completes the instrument.');

  // 11. Measurement Validity
  add(T.validity, 'Measurement validity refers to:', 'Accuracy—how well a score reflects what it is intended to measure', ['Consistency across administrations only', 'Generalizability of the whole study only', 'The size of the sample'], 'Validity concerns accuracy and is a matter of degree: low, moderate, or high.');
  add(T.validity, 'A bathroom scale gives the same weight every time but is always 5 kg too high. It is:', 'Reliable but not valid', ['Valid but not reliable', 'Both valid and reliable', 'Neither measurable nor reliable'], 'It is consistent, but it does not accurately reflect true weight.');
  add(T.validity, 'Content validity asks whether a measure:', 'Representatively samples the intended content and complexity', ['Looks appropriate at a glance', 'Predicts a future criterion', 'Generalizes to another population'], 'Content validity is judged by experts examining coverage of the intended domain.');
  add(T.validity, 'Who commonly establishes content validity?', 'An expert or panel of experts', ['Only the study participants', 'A random-number generator', 'The sample mean'], 'Content validity is a judgmental approach based on knowledgeable review.');
  add(T.validity, 'Face validity means that a measure:', 'Appears appropriate at a superficial glance', ['Has perfect internal consistency', 'Predicts a future outcome', 'Contains every possible item'], 'Face validity is based on appearance, often relevant to participant or public acceptance.');
  add(T.validity, 'A reaction-time task that records milliseconds after a stimulus has strong:', 'Face validity', ['Predictive validity only', 'External validity only', 'Sampling reliability'], 'At a glance, the procedure clearly appears to measure reaction speed.');
  add(T.validity, 'An admissions test is compared with job performance six months later. This assesses:', 'Predictive validity', ['Concurrent validity', 'Face validity', 'Internal consistency'], 'Predictive validity compares an earlier measure with a criterion obtained in the future.');
  add(T.validity, 'A new plaque index and an accepted plaque index are administered at approximately the same time. This assesses:', 'Concurrent validity', ['Predictive validity', 'Content validity', 'Test–retest reliability'], 'Concurrent validity compares the new score with a valid criterion measured at about the same time.');
  add(T.validity, 'Criterion-related validity is supported when:', 'Scores correlate with another valid measure of the same relevant skill, trait, or achievement', ['Experts merely like the appearance of the tool', 'Every item has the same wording', 'The sample represents the population'], 'Criterion validity uses an empirical comparison with a meaningful external criterion.');
  add(T.validity, 'Which correlation indicates a strong inverse relationship?', 'r = −0.90', ['r = 0.01', 'r = 0.20', 'r = 0.90'], 'Values close to −1 indicate a strong negative or inverse association.');
  add(T.validity, 'Construct validity is especially relevant for:', 'A complex theoretical trait such as depression or intelligence', ['A directly counted number of teeth only', 'A participant’s ID number', 'The calendar date'], 'Constructs are collections of related behaviors that require both theory and empirical relationship testing.');
  add(T.validity, 'To support construct validity of a depression scale, researchers might:', 'Predict and test relationships between its scores and variables such as sleep or functioning', ['Only ask whether the scale looks attractive', 'Use the scale once without comparison', 'Replace all items with demographic questions'], 'Construct validation tests theoretically expected relationships with other indicators or variables.');

  // 12. Internal & External Study Validity
  add(T.studyValidity, 'Internal study validity asks:', 'Could something other than the independent variable explain the change in the dependent variable?', ['Can results generalize to other people and settings?', 'Does the tool look accurate?', 'Are the scores consistent over time?'], 'Internal validity concerns credible causal inference within the study.');
  add(T.studyValidity, 'External study validity asks:', 'Can findings generalize from the sample to other people, settings, times, or measures?', ['Did the treatment precede the outcome?', 'Were raters calibrated?', 'Was the null rejected?'], 'External validity is the reach or generalizability of the findings.');
  add(T.studyValidity, 'For a causal conclusion, which condition is required?', 'No confounding or extraneous factor can plausibly explain the result.', ['The treatment must occur after the response.', 'The sample must have zero variability.', 'Every participant must know the hypothesis.'], 'Causality requires covariation, temporal precedence, and elimination of credible alternative explanations.');
  add(T.studyValidity, 'Extremely high pretest scores tend to be less extreme at posttest even without treatment. This is:', 'Regression to the mean', ['Maturation', 'History', 'Instrumentation'], 'Extreme observations often move closer to the mean on repeated measurement.');
  add(T.studyValidity, 'Treatment and control groups differ systematically before treatment because intact clinics were used. This threatens internal validity through:', 'Selection of subjects', ['Testing effects', 'Mortality', 'Face validity'], 'Selection bias creates preexisting group differences that can mimic a treatment effect.');
  add(T.studyValidity, 'Participants naturally become more skilled or tired over time. This threat is:', 'Maturation', ['History', 'Instrumentation', 'Sampling error'], 'Maturation includes natural developmental, physiological, or motivational change during the study.');
  add(T.studyValidity, 'A major news event occurs between pretest and posttest and changes participant behavior. This is:', 'History', ['Maturation', 'Regression to the mean', 'Parallel-forms error'], 'History is an outside event occurring during the study that may affect the outcome.');
  add(T.studyValidity, 'Observers become more lenient when scoring later participants. This is a threat from:', 'Instrumentation', ['Mortality', 'Selection by maturation', 'External replication'], 'A change in measurement procedure or observer behavior can create apparent differences.');
  add(T.studyValidity, 'Taking a pretest teaches participants how to answer the posttest. This is:', 'A testing effect', ['Sampling bias', 'Predictive validity', 'Non-response bias'], 'Repeated testing or pretest sensitization can change later performance.');
  add(T.studyValidity, 'More low-performing participants leave the treatment group than the control group. This is:', 'Mortality or differential attrition', ['Maturation', 'History', 'Face validity'], 'Nonrandom dropout can alter group composition and bias the comparison.');
  add(T.studyValidity, 'Random assignment most directly helps counter:', 'Selection bias by making groups comparable at baseline', ['All measurement error', 'Low face validity', 'The need for a control group'], 'Random assignment balances known and unknown participant characteristics across conditions.');
  add(T.studyValidity, 'A study recruits only one unusually motivated dental-school class. The main external-validity concern is:', 'Sampling bias', ['Instrumentation', 'Regression to the mean', 'Type I error'], 'An unrepresentative sample may not support generalization to the target population.');
  add(T.studyValidity, 'Participants improve oral hygiene because they know they are being observed. This is the:', 'Hawthorne effect', ['John Henry effect', 'Regression effect', 'Criterion effect'], 'The Hawthorne effect is behavior change caused by awareness of observation.');
  add(T.studyValidity, 'Control participants work unusually hard to outperform the treatment group. This is the:', 'John Henry effect', ['Placebo effect', 'History effect', 'Maturation effect'], 'The John Henry effect is compensatory rivalry by a control group that feels disadvantaged.');
  add(T.studyValidity, 'Which strategy broadly strengthens external validity?', 'Replication across settings, populations, and conditions', ['Restricting the sample to one narrow group', 'Eliminating all natural settings', 'Selecting participants only by convenience'], 'Replication tests whether findings hold beyond one particular study context.');
  add(T.studyValidity, 'The classic trade-off is that tightly controlling extraneous variables often improves internal validity but may:', 'Reduce external validity by making the setting less natural or generalizable', ['Eliminate reliability', 'Guarantee Type I error', 'Turn outcomes into nominal data'], 'Highly controlled conditions aid causal inference but can limit real-world generalization.');

  // 13. Evidence & Article Types
  add(T.evidence, 'An original empirical study is considered:', 'A primary source', ['Gray literature by definition', 'A secondary synthesis', 'An expert opinion only'], 'It is written by the researchers who conducted and report the study.');
  add(T.evidence, 'Which feature is strongest evidence that an article reports original research?', 'It presents its own methods, results, and interpretation.', ['It summarizes several studies without new data.', 'It reports one clinician’s opinion.', 'It appears in a news story.'], 'Original research describes the question, methods, collected results, and implications of that same study.');
  add(T.evidence, 'A systematic review primarily:', 'Finds, evaluates, and synthesizes multiple studies using transparent predefined procedures', ['Reports only one newly conducted experiment', 'Collects informal clinical opinions', 'Avoids inclusion and exclusion criteria'], 'Systematic reviews use reproducible searches, explicit selection criteria, quality assessment, and synthesis.');
  add(T.evidence, 'Which is required for a systematic review according to the lecture?', 'An explicit search strategy', ['A single convenience sample', 'No peer review', 'Exclusion of all quantitative studies'], 'Clear inclusion/exclusion criteria and an explicit, reproducible search and coding process are central features.');
  add(T.evidence, 'Meta-analysis in a systematic review is:', 'A quantitative combination of study results when appropriate', ['A list of article titles', 'A replacement for screening studies', 'An interview with one expert'], 'Where studies permit, meta-analysis statistically synthesizes their findings.');
  add(T.evidence, 'Gray literature is information that:', 'Falls outside mainstream commercially published journal and monograph literature', ['Has failed every quality review', 'Contains only qualitative data', 'Is always anonymous'], 'Gray literature describes its publication channel, not necessarily its quality.');
  add(T.evidence, 'Which is an example of gray literature?', 'An unpublished clinical-trial report or conference abstract', ['A standard peer-reviewed original article', 'A commercial textbook chapter', 'A randomized participant list'], 'Conference materials, dissertations, reports, and ongoing or unpublished trials are common gray literature.');
  add(T.evidence, 'A media article discussing someone else’s study is:', 'Not itself original research', ['A primary empirical report', 'A systematic review automatically', 'A measure of construct validity'], 'A summary written by someone who did not conduct and report the study is not the original empirical source.');

  window.STATS_QUESTIONS = bank;
})();
